// Login actionTypes
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// User actionTypes
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';
export const CLEAR_USER_STATE = 'CLEAR_USER_STATE';

// User form actionTypes
export const USER_INPUT_CHANGE = 'USER_INPUT_CHANGE';
export const CLEAR_USER_FORM = 'CLEAR_USER_FORM';

// Farm actionTypes
export const FETCH_FARMS_START = 'FETCH_FARMS_START';
export const FETCH_FARMS_SUCCESS = 'FETCH_FARMS';
export const FETCH_FARMS_FAILED = 'FETCH_FARMS_FAILED';
export const ADD_FARM_FAIL= 'ADD_FARM_FAIL';

// Farm form actionTypes
export const FARM_INPUT_UPDATE = 'FARM_INPUT_UPDATE';
export const CLEAR_FARM_FORM = 'CLEAR_FARM_FORM';

// Data actionTypes
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const ADD_DATA_FAIL = 'ADD_DATA_FAIL';
export const CLEAR_DATA_STATE = 'CLEAR_DATA_STATE';

// Data form actionTypes
export const DATA_INPUT_CHANGE = 'DATA_INPUT_CHANGE';
export const CLEAR_DATA_FORM = 'CLEAR_DATA_FORM';
